"""fixes migrations

Revision ID: 55284ce21114
Revises: b4c632a55d73
Create Date: 2022-12-09 03:54:48.829612

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '55284ce21114'
down_revision = 'b4c632a55d73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_table('walletaccount')
    op.drop_table('question_tags')
    op.drop_table('answer_vote')
    op.drop_table('notification')
    op.drop_table('tag')
    op.drop_table('following')
    op.drop_table('blog')
    op.drop_table('likes')
    op.drop_table('question')
    op.drop_index('email', table_name='user')
    op.drop_index('username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=400), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('work_experience', mysql.VARCHAR(length=400), nullable=True),
    sa.Column('position', mysql.VARCHAR(length=400), nullable=True),
    sa.Column('stack', mysql.VARCHAR(length=400), nullable=True),
    sa.Column('links', mysql.VARCHAR(length=400), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('following', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('followers', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_url', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('account_balance', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('mfa_hash', mysql.VARCHAR(length=300), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'user', ['username'], unique=False)
    op.create_index('email', 'user', ['email'], unique=False)
    op.create_table('question',
    sa.Column('question_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=400), nullable=False),
    sa.Column('content', mysql.VARCHAR(length=2000), nullable=False),
    sa.Column('expected_result', mysql.VARCHAR(length=2000), nullable=False),
    sa.Column('payment_amount', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answered', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('tag', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('total_like', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_unlike', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.user_id'], name='question_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('likes',
    sa.Column('like_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('like_type', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.question_id'], name='likes_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='likes_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('like_id', 'user_id', 'question_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('blog',
    sa.Column('blog_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('body', mysql.VARCHAR(length=7000), nullable=False),
    sa.Column('author', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('image_url', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('post_category', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('date_posted', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('blog_user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['blog_user_id'], ['user.user_id'], name='blog_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blog_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('following',
    sa.Column('user_from', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_user', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['target_user'], ['user.user_id'], name='following_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_from'], ['user.user_id'], name='following_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_from', 'target_user'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tag',
    sa.Column('tag_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tag_name', mysql.VARCHAR(length=40), nullable=False),
    sa.PrimaryKeyConstraint('tag_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('notification',
    sa.Column('notification_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('unread', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['answer.answer_id'], name='notification_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.user_id'], name='notification_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('answer_vote',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vote_type', mysql.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.answer_id'], name='answer_vote_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.user_id'], name='answer_vote_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('question_tags',
    sa.Column('question_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.question_id'], name='question_tags_ibfk_1'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], name='question_tags_ibfk_2'),
    sa.PrimaryKeyConstraint('question_id', 'tag_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('walletaccount',
    sa.Column('id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('balance', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('deposits_made', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('spendings', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='walletaccount_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('answer',
    sa.Column('answer_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', mysql.VARCHAR(length=2000), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('is_answered', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('vote', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.user_id'], name='answer_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.question_id'], name='answer_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('answer_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
